export const get = () => {
	return {
		"Dealer Number": "",
		"Dealer Invoice Number": "",
		"Gross Selling Price": "",
		"Gross Amount of Trade-in (if any)": "",
		"Date of Sale": "",
		"Model Year": "",
		Make: "",
		Model: "",
		"Vehicle Identification Number": "",
		"Trade-in Model Year 1.0": "",
		"Trade-in Model Year 1.1": "",
		"Trade-in Make 1.0": "",
		"Trade-in Make 1.1": "",
		"Trade-in Model 1.0": "",
		"Trade-in Model 1.1": "",
		"Trade-in Vehicle Identification Number 1.0": "",
		"Trade-in Vehicle Identification Number 1.1": "",
		"Purchaser's Name": "",
		"Purchaser's Address": "",
		"Dealer City Sales Tax Account # (if applicable)": "",
		"State of Sale": "",
		"Sales Tax Remitted with DR 0100": "",
		"Use Tax Remitted with DR 0024": "",
		"RTD/SCFD Name.0": "",
		"Tax Rate.0": "",
		"Tax Rate.1": "",
		"Tax Rate.2": "",
		"Tax Rate.3": "",
		"Sales Tax Remitted with DR 0100 1.0.0": "",
		"Sales Tax Remitted with DR 0100 1.0.1": "",
		"Sales Tax Remitted with DR 0100 1.0.2": "",
		"Sales Tax Remitted with DR 0100 1.0.3": "",
		"Use Tax Remitted with DR 0024 1.0.0": "",
		"Use Tax Remitted with DR 0024 1.0.1": "",
		"Use Tax Remitted with DR 0024 1.0.2": "",
		"Use Tax Remitted with DR 0024 1.0.3": "",
		"Statutory City Name (If Applicable)": "",
		"Special District Name": "",
		"County Name": "",
		"Home Rule City Name (if applicable)": "",
		"Taxable Amount": "",
		"Tax Rate Part 3": "",
		"Tax Remitted with DR 0024 Part 3": "",
		"Tax Remitted to City": "",
		'Sum of amounts in Part 2 and 3 Under "Tax Remitted with dR 0024"': "",
		"Dealer/Retailer Address": "",
		"Deale?Retailer Name": "",
		"Net Sales Price": "",
		"DealerRetailer Colorado Sales Tax Account Number": "",
		"Veh Del to Purch Add?": "",
		Comment: "",
		"Net Sales Price 2": "",
	};
};
export type Template = ReturnType<typeof get>;
