export type DR2395_2022_DATA = ReturnType<typeof DR2395_2022>;

export const getDR2395_2022Data = () => {
	return {
		"Vehicle Identification Number VIN_1": "",
		"Vehicle Identification Number VIN_2": "",
		"Vehicle Identification Number VIN_3": "",
		"Vehicle Identification Number VIN_4": "",
		"Vehicle Identification Number VIN_5": "",
		"Vehicle Identification Number VIN_6": "",
		"Vehicle Identification Number VIN_7": "",
		"Vehicle Identification Number VIN_8": "",
		"Vehicle Identification Number VIN_9": "",
		"Vehicle Identification Number VIN_10": "",
		"Vehicle Identification Number VIN_11": "",
		"Vehicle Identification Number VIN_12": "",
		"Vehicle Identification Number VIN_13": "",
		"Vehicle Identification Number VIN_14": "",
		"Vehicle Identification Number VIN_15": "",
		"Vehicle Identification Number VIN_16": "",
		"Vehicle Identification Number VIN_17": "",
		"If electric is it plug-in electric": "",
		Year: "",
		Make: "",
		Body: "",
		Model: "",
		Color: "",
		CWT: "",
		"Off-Highway Vehicle": "",
		Snowmobile: "",
		"Dealer #": "",
		"Date Purchased": "",
		MSRP: "",
		"Size W x L": "",
		"Bus Cap": "",
		"Legal Names as it Appears on Identification and Physical Address Owner's or Enity":
			"",
		"DR 2421 Attached": "",
		"Lease Buy-Out": "",
		"Legal Names as it Appears on Identification and Physical Address of Lessee":
			"",
		"Indicate Alternate Address Here if The Registration Renewal Should be Sent to a Different Address":
			"",
		"First Lienholder Name and Address": "",
		"Lien Amount": "",
		"Second Lienholder Name and Address": "",
		"Lien Amount_2": "",
		"Indicate Alternate Address Here if The Title Should be Sent to a Different Lienholder Address":
			"",
		"Indicate Alternate Address Here if The Title Should be Sent to a Different Lienholder Address_2":
			"",
		Date: "",
		"Printed name of OwnerAgent as it appears on Identification:": "",
		"Colorado DL": "",
		"Colorado ID": "",
		Other: "",
		Other_1: "",
		"ID #": "",
		Expires: "",
		DOB: "",
		Date_2: "",
		"Previous Title Number": "",
		"Title Number": "",
		"Date Accepted": "",
		"Purchase Price": "",
		"Odometer Reading Indicator": "",
		GVWR: "",
		"Fleet #": "",
		"Unit #": "",
		"First Lienholder": "",
		"Second Lienholder": "",
		"Lien File No._1": "",
		"Lien File No._2": "",
		"Lien Amount_3": "",
		"Maturity Date": "",
		"Date of Lien": "",
		"Lien Amount_4": "",
		"Maturity Date_2": "",
		"Date of Lien_2": "",
		"Taxes Paid": "",
		"Filing Fees": "",
		"Additional Comments": "",
		"Clerks Initials": "",
		"Owner or Agent Signature": "",
		"Witness Signature": "",
		"Vehicle Identification Number": "",
		Year_2: "",
		Make_2: "",
		Model_2: "",
		I_1: "",
		"Joint Tenancy With Rights of Survivorship_1": "",
		"Tenancy in Common_1": "",
		Date_3: "",
		I_2: "",
		"Joint Tenancy With Rights of Survivorship_2": "",
		"Tenancy in Common_2": "",
		Date_4: "",
		I_3: "",
		"Joint Tenancy With Rights of Survivorship_3": "",
		"Tenancy in Common_3": "",
		Date_5: "",
		Signature1: "",
		Signature2: "",
		Signature3: "",
		"Flex Fuel": "",
		"Fuel Type": "",
		"Witness Printed Name": "",
		"Commercial Use": "0",
		"Keep Colorado Wild": "No",
	};
};
